Table users {
  id integer [primary key]
  username varchar
  role varchar [note: 'will we even have multiple roles?']
  created_at timestamp
}

Table campaign {
  id integer [primary key]
  title varchar
  notes text
  user_id integer
  status bool
  created_at timestamp
}

Table test {
  id integer [primary key]
  title varchar
  content varchar [note: 'Email content']
  sender varchar [note: 'Sender address']
  camp_id integer
  status bool
  created_at timestamp
}

Ref: campaign.user_id > users.id
Ref: campaign.id < test.camp_id
